apiVersion : apps/v1
kind: Deployment
metadata:
  name: komodor-demo 
spec:
  replicas: #REPLICAS#
  selector:
    matchLabels:
      app: komodor-demo
  template:
    metadata:
      labels:
        app: komodor-demo 
    spec:
      containers:
        - name: komodor-demo 
          image: acrdbtekdev.azurecr.io/komodor-demo
          ports:
          - containerPort: 80